version: '3.1'

services:
  #mariadb container
  database:
    image: mariadb:10.3
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: nrhb_spatial
      MARIADB_USER: nrhb
      MARIADB_PASSWORD: secret
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    networks:
      - nrhb-net

  #phpMyAdmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    networks:
      - nrhb-net
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database

networks:
  nrhb-net:
